### ISSUE TITLE
kongCredential type acl doesn't work

### ISSUE THREAD

**Issue by dcherniv** [Kong/kubernetes-ingress-controller#215]
### Summary

kongCredential of type acl doesn't work properly.

**Kong Ingress controller version**
0.2.2

**Kong or Kong Enterprise version**
kong

### Kubernetes version
`Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T21:04:45Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.9-gke.5", GitCommit:"d776b4deeb3655fa4b8f4e8e7e4651d00c5f4a98", GitTreeState:"clean", BuildDate:"2018-11-08T20:33:00Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}`

### Environment

gke
cOS

### What happened
When kongCredential type acl was created as follows:
```
apiVersion: configuration.konghq.com/v1
consumerRef: lfs-others
group: lfs
kind: KongCredential
metadata:
  name: lfs-group
  namespace: dev
config:
  group: lfs
type: acl
```
The group was not created and/or assigned to the corresponding consumer, instead there was an error from the ingress controller as follows:
`requeuing dev/lfs-group, err entity 'acl' not registered`

### Expected behavior
Consumer assigned an acl group

### Steps To Reproduce

create consumer:
```
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: lfs-others
  namespace: dev
username: lfs-others
```
create acl plugin
```
apiVersion: configuration.konghq.com/v1
config:
  whitelist: lfs
disabled: false
kind: KongPlugin
metadata:
  name: lfs-acl
  namespace: dev
plugin: acl
```
create kongcredential:
```
apiVersion: configuration.konghq.com/v1
consumerRef: lfs-others
group: lfs
kind: KongCredential
metadata:
  name: lfs-group
  namespace: dev
config:
  group: lfs
type: acl
```

**Comment by hbagdi** [comment]
This should be fixed with 0.3.0

**Comment by monson** [comment]
@hbagdi Do we know, when this would be available for enterprise version.

**Comment by dcherniv** [comment]
0.3.0 is out @monson this is purely the ingress controller issue has no relation to kong itself.

**Comment by monson** [comment]
@dcherniv Thanks. The version matrix says the supported versions with enterprise editions and 0.3.0 is still not supported with the enterprise version.
 https://github.com/Kong/kubernetes-ingress-controller#version-support-matrix
